FROM mariadb:latest
ENV MARIADB_USER=udada
ENV MARIADB_PASSWORD=
ENV MARIADB_ROOT_PASSWORD=
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt upgrade -y